apiVersion: v1
kind: Service
metadata:
  name: {{ include "sanchr.fullname" . }}-core
  labels:
    {{- include "sanchr.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
spec:
  type: {{ .Values.core.service.type }}
  ports:
    - port: {{ .Values.core.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.core.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sanchr.core.selectorLabels" . | nindent 4 }}
